### ISSUE TITLE
High DPI Screens scaling

### ISSUE THREAD

**Issue by brasilikum** [balena-io-projects/balena-dash#11]
Hey,

I would like to know if there is any way to make things I show on the Dashboard bigger.
I could think of
- Lowering the Resolution
- Changing the browsers scaling factor

I investigated a little on WPE but could not find how to do this. Does someone know if it's possible?

**Comment by chrisys** [comment]
@brasilikum if this works or not may depend a little on what display you're using, but you can force the output to a particular resolution using configuration variables. I explained how to do this in this post (look for mentions of `hdmi_cvt`): https://www.balena.io/blog/add-a-cheap-ili9341-lcd-to-your-resin-io-raspberry-pi-project/
