### ISSUE TITLE
Change timezone in wpe

### ISSUE THREAD

**Issue by marhoy** [balena-io-projects/balena-dash#16]
My web dashboard uses the local time of the browser to display the current time on the webpage. But the wpe images uses the same timezone as the host: UTC.

How can I change the timezone in the wpe container?
Since it's not based on Debian, the idea from https://github.com/balena-io-playground/balena-timezone does not work.

**Comment by marhoy** [comment]
If someone have the same problem and reads this: I figured out that Busybox (used in the resin-wpe image) has a different format for the TZ-variable. For Europe, I'm using
`TZ=CET-1CEST`

**Comment by rjoel98** [comment]
Hi, I am having similar issues. Would you mind going into a little more detail as to how/where you found this solution? Everything I can find from BusyBox about time zones says that it doesn't handle them at all, which seems odd. Any help would be amazing. Thanks you.

**Comment by marhoy** [comment]
@rjoel98 You would have to use [the libc way of specifying timezones](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html).

**But:** After I struggled with this, I decided to rather update the docker image with wpewebkit. I've made a [pull request for balena-wpe](https://github.com/balena-io-projects/balena-wpe/pull/41) that e.g updates the browser to a more recent version and adds timezone support. And I've compiled a docker-image that is a drop-in replacement for the current one.

**So:** In your `wpe/Dockerfile`, just replace `petrosagg/resin-wpe:raspberrypi3-30c7465` with `marhoy/balena-wpe:2.22-latest`. Then, you can use normal tz-strings like e.g. TZ=Europe/Oslo.

1. I'm hoping that the PR will be accepted soon, as I have no intention of taking over the project (@petrosagg, @imrehg ?).
2. I'm also working on compiling an image with wpewebkit-2.24.2, using poky warrior. But I currently have some issues with GnutTLS and https-certificates.

**Comment by rjoel98** [comment]
@marhoy It looks like you have been doing to lot, so thank you for your hard work on this project. 

Unfortunately, when I made the change that you described above, my pi is now stuck on the balena loading screen and will not display the site at all. 

This is my first time working with a something like this, so it's possible I did/didn't do something, but regardless I am stuck. Any help would be greatly appreciated. Thank you!

**Comment by marhoy** [comment]
Hi,

In order for the image to do anything, you have to set the environment variable WPE_URL to the URL you want to display (starting with http).

And the wpe-container needs to run privileged, so make sure you docker-compose.yml looks something like this:
```
  wpe:
    build: ./balena-wpe
    privileged: true
    ports:
      - 8080:8080
```

You can point a browser at `http://your_balena_dash:8080` in order to temporarily display other URLs. 

You can also set RPI_BACKLIGHT to a value between 0 and 255 to change the brightness of the screen.

You the balena dashboard to see log messages from the container and to log in and poke around.

**Comment by rjoel98** [comment]
My apologies, I do not believe I was fully clear as to what occurred when I made the update that you suggested [here](https://github.com/balena-io-projects/balena-dash/issues/16#issuecomment-495976010).

What happened was, I was running the version of balena-dash as is from the git repository, and it was displaying the webpage perfectly... well minus the wrong time, so almost perfectly. Then once I replaced `petrosagg/resin-wpe:raspberrypi3-30c7465` with `marhoy/balena-wpe:2.22-latest` and pushed the update to my application, the pi returned to the balena loading screen while updating, then it just stopped. Now the pi is responsive, and I can view the logs, and even restart it from the console, but it will not display the webpage that is specified under `WPE_URL`. And there is nothing in the logs that would suggest why it isn't loading. Any suggestions as to what might be happening?

**Comment by marhoy** [comment]
I'm sorry, but the above does not contain sufficient information to debug the problem.
Can you post the log from the wpe container? (as seen from the balena dashboard).
There should be at least some lines output when it starts.

You can also log into the wpe container, run `/wpe-init` manually and see what happens.

**Comment by rjoel98** [comment]
My apologies, I don't know why I didn't use the filter last time on the logs. Thank you for your patience as I figure out what I am doing, haha.

Anyways, here is what I found in the logs for `WPE`

   `28.05.19 9:41:10 (-0600)  wpe  /wpe-init: line 8: WPELauncher: command not found 
   28.05.19 9:41:10 (-0600)  wpe  2019/05/28 15:41:10 Command is 'WPELauncher'
   28.05.19 9:41:10 (-0600)  wpe  2019/05/28 15:41:10 Starting listening on port 8080`

But even when I try replacing  `WPELauncher` with `'WPELauncher'` on line 8 of `/wpe-init` I get the same error.

So I also took your suggestion of trying it through the terminal, and this is what I got in return 

`line 8: WPELauncher: command not found  
2019/05/28 15:48:25 Command is 'WPELauncher'  
2019/05/28 15:48:25 Starting listening on port 8080  
2019/05/28 15:48:25 listen tcp :8080: bind: address already in use`  

Any suggestions/ideas as to why this is happening?

**Comment by marhoy** [comment]
@rjoel98 In the latest releases, `/wpe-init` is not starting `WPELaucher`, it starts `cog`. So you seem to somehow be running a mixture of old and new code. Are you manually overriding `CMD` or `ENTRYPOINT`?

And you already have something else in the same container running on port 8080.

Please review your configuration.

**Comment by rjoel98** [comment]
@marhoy My apologies, I completely forgot that I was referred to this thread from the [Balena Forms](https://forums.balena.io/t/setting-the-time-on-a-raspberry-pi/11455/9). Which is talking about balena-dash, and it appears to use an older version of wpe. But when I ran the files from the directory [balena-wpe](https://github.com/balena-io-projects/balena-wpe) it worked! Now the last step is how/where do I add the timezone configuration to the file?

Sorry again about the confusion, and thank you so much for your patience!

**Comment by marhoy** [comment]
@rjoel98 Here's two ways to set the TZ environment variable:
- In your [docker-compose file](https://docs.docker.com/compose/compose-file/compose-file-v2/#environment)
- Via the [Balena dashboard](https://www.balena.io/docs/learn/manage/serv-vars/#environment-and-service-variables)

**Comment by rjoel98** [comment]
Perfect, thank you so much! @marhoy
