### ISSUE TITLE
Can you use this project without the raspberry pi display?

### ISSUE THREAD

**Issue by dauledk** [balena-io-projects/balena-dash#2]

**Comment by chrisys** [comment]
@dauledk, sure! Any HDMI display will work just as well.

**Comment by menarcarlos** [comment]
I Have the same issue, can give us a guide to change the video output to hdmi screen.
Thanks.

**Comment by guile2912** [comment]
I would also be interested in the procedure to have this work on a HDMI screen. With a HDMI screen plugged in and the code deployed, the screen just show the Balena OS ASCII art.

**Comment by theaccordance** [comment]
I think I had a similar issue when I attempted to use an older Raspberry PI (1 B+).  I didn't try to troubleshoot further, simply went to a newer board.
