### ISSUE TITLE
Container keeps restarting if WPE_URL is undefined

### ISSUE THREAD

**Issue by edorgeville** [balena-io-projects/balena-dash#27]
https://github.com/balena-io-projects/balena-dash/blob/32361d047ccb99f9f4f694583f716ab69ff2f0cf/wpe/wpe-init#L41-L45

This block will be skipped if `WPE_URL` is not set, leading to the script exiting, leading to the container restarting forever.

The solution would be to add an else statement to [the previous block](https://github.com/balena-io-projects/balena-dash/blob/32361d047ccb99f9f4f694583f716ab69ff2f0cf/wpe/wpe-init#L32-L39), setting a default URL [as stated in the README](https://github.com/balena-io-projects/balena-dash/blob/master/README.md#loading-a-url): 

> The default value is [Youtube TV](http://www.youtube.com/tv)

Here is the thread explaining all the steps it took me to get here 😅 : https://forums.balena.io/t/logbackend-server-responded-with-status-code-504/22564/18

**Comment by dansku** [comment]
Hey @edorgeville thank you very much for the issue. We've fixed the issue on the [here](https://github.com/balena-io-projects/balena-dash/pull/28).

Can you give it a go and report back to confirm that it is also working on your end?

Thank you!
