### ISSUE TITLE
Installing the Balena-Cli not working

### ISSUE THREAD

**Issue by dominicbed** [balena-io-projects/balena-dash#6]
Hi i am trying to install the balena-cli with the comands shown on the video but when i type it it shows this

root@1d0396d:~# npm install balena-cli -g
bash: npm: command not found

can some one help me?

**Comment by chrisys** [comment]
@dominicbed firstly where are you running this command? Just to clarify you'll want to install the balena-cli tools on your own workstation as this is where you'll want to push code from.

Secondly, you're getting that error as npm (Node package manager) is not installed wherever you're running that command. As balena-cli is a node package, you'll need to install npm first -- it comes with Node.js: https://nodejs.org/en/

I hope this helps!

**Comment by dominicbed** [comment]
I am running this command here, because i dont know where else to run it
![gfsdd](https://user-images.githubusercontent.com/46569025/51912017-3ce72980-23a1-11e9-9611-9f0d6d813e3a.jpg)

i try to install nodejs on the terminal but 
![image](https://user-images.githubusercontent.com/46569025/51912124-86377900-23a1-11e9-83b5-c047736b5c54.png)

thanks for the help

**Comment by dominicbed** [comment]
npm WARN balena-request@10.0.1 requires a peer of balena-auth@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN resin-register-device@5.0.0 requires a peer of resin-request@^9.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macmount@1.0.0 (node_modules\balena-cli\node_modules\macmount):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macmount@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drivelist@6.4.6 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drivelist@6.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dbedard.SBINTL\AppData\Roaming\npm-cache\_logs\2019-01-29T14_11_27_765Z-debug.log

C:\Users\dbedard.SBINTL>balena --version
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'C:\Users\dbedard.SBINTL\AppData\Roaming\npm\node_modules\balena-cli\bin\balena'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

I think i need to execute it from cmd but still i get this error, i already installed python and Nodejs

**Comment by chrisys** [comment]
@dominicbed you could also try the precompiled binaries for the CLI as you're using Windows. They're available here: https://github.com/balena-io/balena-cli/releases

**Comment by dominicbed** [comment]
Works! thanks a lot
