### ISSUE TITLE
Confirm whether balenaDash works with earlier RPi models

### ISSUE THREAD

**Issue by pdcastro** [balena-io-projects/balena-dash#9]
Although the project docs state that an RPi 3B is required, some users were trying to run it on earlier RPi models and the question was raised on the reason why the project shouldn't work on earlier RPi models.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h8lf)

**Comment by chrisys** [comment]
@pdcastro RAM is the main reason; as long as the device has 1GB it *should* work.

**Comment by pdcastro** [comment]
@chrisys, thanks! So perhaps, until/unless new requirements become known, the balenaDash documentation could be updated to say that the project requires "an RPi with at least 1GB RAM"? (Could also add in brackets that it was tested mainly with an RPi 3B.)
